name: Lint Python

on: [push]

jobs:
  call-run-python-linters:
    uses: openclimatefix/.github/.github/workflows/python-lint.yml@e67a64b086a5662c39f6b4523a97dd0641904279
    with:
      folder: "solar_and_storage"
